import Alert from "@/components/Alert";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-green-50`}
      >
        {" "}
        <div className="z-10">
          <Alert />
        </div>
        {/* <Navbar /> */}
        <div className="z-10 text-black  backdrop-blur-xs sticky top-0 left-0 w-auto">
          <Navbar />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
